default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout:  5000
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host:     <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] if ENV['LOCAL'].blank? %>
  port:     <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] if ENV['LOCAL'].blank? %>

development:
  <<: *default

test:
  <<: *default
  database: femida_test

production:
  <<: *default
